config/routes.rb
Rails.application.routes.draw do

  root to: 'application#welcome'

  resources :purchases, only: [:index, :new, :create, :edit, :destroy, :show]

  resources :products, only: [:index, :new, :create, :edit, :destroy]
  
  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "callbacks"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :user do
    get 'login', to: 'devise/sesssions#new'
  end
  
  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

    validates :name, presence: true, length: { maximum: 20}, uniqueness: true
    validates :price, presence: true, length: {maximum: 6}

    has_many :purchases
    has_many :users, through: :purchases

end

app/models/purchase.rb
class Purchase < ApplicationRecord

    validates :date, presence: true, length: { maximum: 150}
    validates :vendor, presence: true, length: { maximum: 20}
    validates :quantity, presence: true

    belongs_to :user
    belongs_to :product 

    #accepts_nested_attributes_for :product

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:

  validates :name, presence: true, uniqueness: { case_sensitive: false }

  has_many :purchases
  has_many :products, through: :purchases 

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.name = auth.info.name
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def welcome
    end
    
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController

    def github
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end 
    
end 

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    #before_action :set_product, only: [:index, :new]
    
    def index
        @products = Product.all
        @user = current_user
    end

    def new
        @product = Product.new
    end

    def create
        @product = Product.create(product_params)
        redirect_to product_path(@product)
    end

    def update
        @product.update(product_params)
        redirect_to product_path(@aproduct)
    end

    private

    def product_params
        params.require(:product).permit(:name)
    end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
    before_action :set_user

    def index
        @purchases = @user.purchases
    end

    def show
        @purchase = Purchase.find(params[:id])
    end

    def new
        @purchase = Purchase.new
        @purchase.product = Product.new
        @products = Product.all
    end

    def edit
        @purchase = Purchase.find(params[:id])
    end

    def create
        @purchase = @user.purchases.create(purchase_params)
        redirect_to purchases_path
    end

    def destroy
        purchase = Purchase.find(params[:id])
        if purchase.user == current_user
            purchase.destroy
        end
        redirect_to purchases_path
    end

    private

    def set_user
        @user = current_user
    end

    def purchase_params
        params.require(:purchase).permit(:product_id, :product_name, :date, :quantity, :vendor)
    end
    
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
        params.require(:user).permit( :name,
                                      :email,
                                      :password,
                                      :password_confirmation)
    end 

    def account_update_params
        params.require(:user).permit( :name,
                                      :email,
                                      :password,
                                      :password_confirmation,
                                      :current_password)
    end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/application/welcome.html.erb
<h1>Welcome to Purchase Tracker</h1> 
<div class="container" style="float: left">
  <header><img src="https://lh3.googleusercontent.com/proxy/lZPdqDs98b4p7Z2pPpG8mFwwjIWZV2WSm_rg6_MJLdooTvqEVI7f6pfIZUj26q1mExomjP8cMnJiMB4cRt1D4GXtGlsRKWzYmpq3zIU-ZrHard4N5T_GQ5Dwz2HuK-NfxSMgXEC2xQCE98TOpw" width="400" height=200 class="img-responsive main-image">
  

<% if user_signed_in? %>
    <h2> Logged in as <%= current_user.name %></h2>
    <h2> Your Purchase History: <%= link_to 'Here', purchases_path %></h2>
    <h2> Record a New Purchase: <%= link_to 'Here', new_purchase_path %> </h2>

<% else %>
    <h2> Please Signup or Login to Use Purchase Tracker. <h2>
<% end %>
</div>

app/views/layouts/_nav.html.erb
<nav>

    <ul>
        <li><%= link_to "Home", root_path %></li>
        <% if !user_signed_in? %>
            <li><%= link_to "Signup", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
        <% else %>
            <li><%= current_user.email %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method:"delete" %></li>
        <% end %>
    </ul>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PurchaseTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/products/new.html.erb
<h1>Enter a New Product</h1>

<%= form_for(@product) do |f| %>

        <%= f.text_field :name, placeholder: 'name' %><br>
        <br><%= f.submit %>

<% end %>

app/views/purchases/_form.html.erb
<%= form_for(@purchase) do |f| %>

        <%= f.collection_select :product_id, Product.all, :id, :name, placeholder: 'Product Name' %><br>
        <%= f.text_field :date, placeholder: 'date' %><br>
        <%= f.text_field :quantity, placeholder: 'quantity' %><br>
        <%= f.text_field :vendor, placeholder: 'vendor' %><br>
        <br><%= f.submit %>

<% end %>

app/views/purchases/edit.html.erb
<h1>Editing Purchase</h1>

<%= render 'form', purchase: @purchase %>

<%= link_to 'Show', @purchase %> |
<%= link_to 'Back', purchases_path %>

app/views/purchases/index.html.erb
<h1>Your Purchase History</h1>
<div>
    <% @user.purchases.each do |purchase| %>
        <div class="wrapper" style="border: 2px solid black">
        <%= purchase.product.name %><br>
        <%= purchase.date %><br>
        <%= link_to 'Details', purchase %><br>
        <%= link_to 'Edit', edit_purchase_path(purchase) %><br>
        <%= link_to 'Delete', purchase, method: :delete, data: { confirm: 'Are you sure?' } %></div><br>
    <% end %>
</div>

app/views/purchases/new.html.erb
<h1>New Purchase</h1>

<%= render 'form', purchase: @purchase %>

<%= link_to 'Enter a New Product', new_product_path%><br>

<%= link_to 'Back', purchases_path %>

app/views/purchases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @purchase.date %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @purchase.quantity %> Kg.
</p>

<p>
  <strong>Vendor:</strong>
  <%= @purchase.vendor %>
</p>

<p>
  <strong>User:</strong>
  <%= @purchase.user_id %>
</p>

<p>
  <strong>Product name:</strong>
  <%= @purchase.product_name %>
</p>

<p>
  <strong>Product:</strong>
  <%= @purchase.product_id %>
</p>

<%= link_to 'Edit', edit_purchase_path(@purchase) %> |
<%= link_to 'Back', purchases_path %>